"""Create models

Revision ID: 5028f194dc8f
Revises: 57881204f4e6
Create Date: 2023-11-22 12:07:33.364360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5028f194dc8f'
down_revision = '57881204f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
